Traceback (most recent call last):
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/runcode/RunCode.py", line 36, in execute_code
    exec(compile(parse, filename="<ast>", mode="exec"), loc)
  File "<ast>", line 51, in <module>
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/pipeline.py", line 602, in predict
    Xt = transform.transform(Xt)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 1014, in transform
    Xs = self._call_func_on_transformers(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 823, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/pipeline.py", line 1283, in _transform_one
    res = transformer.transform(X, **params.transform)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py", line 1023, in transform
    X_int, X_mask = self._transform(
                    ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py", line 213, in _transform
    raise ValueError(msg)
ValueError: Found unknown categories [-2207.0, -2144.0, -2103.0, -1883.0, -1681.0, -1647.0, -1631.0, -1614.0, -1551.0, -1545.0, -1516.0, -1500.0, -1497.0, -1492.0, -1491.0, -1469.0, -1468.0, -1463.0, -1448.0, -1429.0, -1427.0, -1415.0, -1413.0, -1412.0, -1405.0, -1403.0, -1397.0, -1392.0, -1376.0, -1363.0, -1358.0, -1332.0, -1327.0, -1315.0, -1300.0, -1297.0, -1292.0, -1291.0, -1290.0, -1288.0, -1283.0, -1279.0, -1278.0, -1273.0, -1267.0, -1261.0, -1258.0, -1243.0, -1236.0, -1217.0, -1211.0, -1209.0, -1203.0, -1197.0, -1190.0, -1189.0, -1180.0, -1175.0, -1119.0, -1109.0, -1102.0, -1101.0, -1094.0, -1085.0, -1065.0, -1060.0, 1292.0, 1321.0, 1322.0, 1328.0, 1370.0, 1374.0, 1381.0, 1387.0, 1391.0, 1397.0, 1399.0, 1403.0, 1420.0, 1429.0, 1436.0, 1445.0, 1463.0, 1478.0, 1487.0, 1490.0, 1496.0, 1505.0, 1523.0, 1524.0, 1546.0, 1565.0, 1590.0, 1623.0, 1643.0, 1649.0, 1712.0, 1735.0, 1758.0, 1765.0, 1778.0, 1815.0, 1833.0, 1930.0, 2246.0, 2343.0] in column 0 during transform
